---
- name: Configure core VM
  hosts: core
  become: true
  gather_facts: true
  roles:
    - common
    - docker
    - { role: atlas, tags: atlas }
    - { role: polaris, tags: polaris }
    - { role: harmony, tags: harmony }
