---
- name: Configure edge VM
  hosts: edge
  become: true
  gather_facts: true
  roles:
    - common
    - docker
    - { role: tycho, tags: tycho }
    - { role: janus, tags: janus }
    - { role: harmony, tags: harmony }
