---
- name: Configure services VM
  hosts: services
  become: true
  gather_facts: true
  roles:
    - common
    - docker
    - { role: gaia, tags: gaia }
    - { role: echo, tags: echo }
    - { role: rosetta, tags: rosetta }
