---
dns_records:
  - { name: vanguard.x, address: 'fd22:1337:6769:10::1' }
  - { name: sol.x, address: 'fd22:1337:6769:10::2' }
  - { name: core.sol.x, address: 'fd22:1337:6769:30::3' }
  - { name: services.sol.x, address: 'fd22:1337:6769:30::4' }
  - { name: polaris.x, address: 'fd22:1337:6769:30::3' }
  - { name: atlas.x, address: 'fd22:1337:6769:30::3' }
  - { name: ca.x, address: 'fd22:1337:6769:30::3' }
  - { name: unity.x, address: 'fd22:1337:6769:30::3' }
  # UniFi devices hardcode discovery to the bare name `unifi`
  - { name: unifi, address: 'fd22:1337:6769:30::4' }
